### ISSUE TITLE
A place for user to submit custom kc3kai skins and share it with others.

### ISSUE THREAD

**Issue by weejiaquan** [KC3Kai/KC3Kai#1078]
I have an idea of creating a subreddit for anyone that want to submit their own skins for kc3kai for other player to use it. For example i will upload my skins onto imgur (bg + panel) and then link the screenshot to the reddit with link to paste inside kc3kai setting in the description.

Something like this: 
http://imgur.com/a/swP4t

**Comment by dragonjet** [comment]
but for the panel's background image, what if it goes vertical?

**Comment by LostLogia4** [comment]
hmm, can't we just provide an alternate image for horizontal and vertical panel?

**Comment by dragonjet** [comment]
hm I'm not sure, what I visualize for the suggestion is to do something like a public thread where people can post the settings format, without any additions to the app code.

**Comment by weejiaquan** [comment]
@dragonjet I've uploaded some of them here. http://weejiaquan.imgur.com/

Maybe a page in wikia where player can link their imgur album for skins?

**Comment by kololz** [comment]
K took a look on your nice skin setups
Actually this isn't a bad idea, you might make the skin submission page like a library, like how ship list is done, you can sort them you like or remove unwanted ones (i.e. Remove those skins for bottom panel as you'd like to go with vertical ones)

**Comment by ReiFan49** [comment]
i think the background can be done by having it's own element though,
which looks like this, at the top of the wrapper element
```HTML
<div class=panel-background>
    <div class="background v"></div>
    <div class="background h"></div>
</div>
```
and have the style that looks like this
```CSS
.panel-background .background {
  position:absolute;
  top:0;
  left:0;
  width:100%;
  height:100%;
  display:none;
}
```

with the responsive css rule or js based responsivity that currently natsuiro use..
```CSS
@media only screen and (min-width:800px) {
  .panel-background .background.v { display:block; }
}
@media only screen and (max-width:799px) {
  .panel-background .background.h { display:block; }
}
```
or
```CSS
.wrapper.h .panel-background .background.h {
  display:block;
}
.wrapper.v .panel-background .background.v {
  display:block;
}
```

providing a same background for vertical and horizontal will make the panel-background not really used though...
