### ISSUE TITLE
ship avatar low quality in chrome61

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#2226]
chrome55 no problem, problem with chrome 61. the chrome ver between them is not tested.

**Comment by mikenzb** [comment]
Can you screenshot a example for us?

**Comment by sinsinpub** [comment]
as a workaround for now, u can add this custom CSS to settings (panel / strategy room)
```css
img { image-rendering:-webkit-optimize-contrast; }
```
